# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff74ddf149942746163dbbbfda3fd12766a2bcf244fadd50097dff62e02023ff47449d15e47be5298950f7f84ab6277744f2ec39eb7601e635b7192c0013851

test:
  secret_key_base: a310d5744840fc6732f2f3366b2e5bc4772e2c94cfa00b9adb1c54bda4cab4d57a4f578d287b19e8358535e7560c2a6f62d38bcc806720518b9d7730fe78298b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
